apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-kibana
  namespace: elasticsearch
  labels:
    component: elasticsearch
    role: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: kibana
    spec:
      containers:
      - name: es-kibana
        imagePullPolicy: Always
        image: akhilrajmailbox/elasticsearch:kibana-oss-6.2.4
        # image: docker.elastic.co/kibana/kibana-oss:6.2.2
        env:
        - name : KIBANA_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
                name: es-auth-cm
                key: KIBANA_ADMIN_PASSWORD

        - name: CLUSTER_NAME
          value: my-es
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
        ports:
        - containerPort: 5601
          name: http